model:
  base_learning_rate: 1e-4   # set to target_lr by starting main.py with '--scale_lr False'
  target: daf_net.dafnet.DAFNetLightning
  params:
    modalities: ['cine', 'psir']
    num_masks: 2
    learning_rate: 1e-4
    automated_pairing: false
    use_swa: true
    swa_start_epoch: 40
    swa_freq: 1
    
    scheduler_config: # 10000 warmup steps
      target: functions.lr_scheduler.LambdaLinearScheduler
      params:
        # warm_up_steps: [10000]
        warm_up_steps: [1000]
        cycle_lengths: [10000000000000]
        # f_start: [1.e-6]
        f_start: [0.1]
        f_max: [1.]
        f_min: [1.]

    loss_weights:
      w_sup_M: 10.0
      w_adv_M: 1.0
      w_rec_X: 1.0
      w_adv_X: 1.0
      w_kl: 0.1
      w_rec_Z: 1.0
    
    anatomy_encoder_config:
      target: models.anatomy_encoder.AnatomyEncoders
      params:
        modalities: ['cine', 'psir']
        in_channels: 1
        out_channels: 8
        base_channels: 64
        ch_mult: [1, 2, 4, 8, 16]
        norm_type: batch
        use_rounding: true
        bilinear: true
    
    modality_encoder_config:
      target: models.modality_encoder.ModalityEncoder
      params:
        resolution: 128
        in_channels: 1
        base_channels: 64
        anatomy_channels: 8
        ch_mult: [1, 2, 4, 8]
        latent_dim: 8
    
    segmentor_params_config:
      target: models.segmentor.Segmentor
      params:
        in_channels: 8
        num_classes: 2
        base_channels: 64
    
    # decoder_params_config:
    #   target: models.decoder.Decoder
    #   params:
    #     decoder_type: film
    #     decoder_params:
    #       in_channels: 8
    #       base_channels: 64
    #       modality_dim: 8
    #       num_layers: 4
    #     out_channels: 64

    decoder_params_config:
      target: models.decoder.Decoder
      params:
        decoder_type: spade
        decoder_params:
            resolution: 128  # the spatial resolution of the anatomy factor/ or the image
            base_channels: 128  # base channels of the SPADE blocks
            condition_channels: 8  # the anatomy factor will be set as the condition, the channels are equal to the number of anatomy factors
            ch_div: [1, 1, 1, 2, 4, 4]  # the channels division of the SPADE blocks
        out_channels: 32

    anatomy_fuser_config:
      target: models.anatomy_fuser.AnatomyFuser
      params:
        in_channels: 8
        resolution: 128
        control_points: [5, 5]
        order: 2
    
    d_mask_params:
        in_channels: 2
        resolution: 128
        base_channels: 16
        ch_mult: [1, 2, 4, 8]
        use_spectral_norm: True
    
    d_image_params:
        in_channels: 1
        resolution: 128
        base_channels: 16
        ch_mult: [1, 2, 4, 8, 16]
        use_spectral_norm: True

data:
  target: dataset.inhouse_module.HCMDataModule
  params:
    dataset_type: DCM
    mandatory_protocols: ['cine', 'psir']
    dataset_dirpath: /public_bme2/bme-qihk/liaohx/PROJECTS/Cine_Generated_Enhancement/Data/ZCMU_DCM
    batch_size: 24
    num_workers: 4
    without_rightventricular: True
    roi_fixed_pixel_spacing: [0.89, 0.89]
    roi_resample_size: [128, 128]
    modality_vec_dim: 8
    training_groups: [
            'internal_batch1',
            'internal_batch2',
            'internal_batch3',
            'internal_batch4',
            'internal_batch5',
            'internal_batch6',
            'internal_batch7',
            'internal_batch8',
            'internal_batch9',
            'internal_batch0',
            'external_Z1',
      ]
    testing_groups: [
            'internal_batch0',
            'external_Z1',
      ]
    train_criteria : [
            'basic',
            'high_quality_cine',
            'high_quality_psir',
            # 'recognizable_psir',
            'cine_aligned',
            'without_apex_position',
            'without_base_position',
            ]
    test_criteria: [
            'basic',
            'high_quality_cine',
            'cine_aligned',
            'without_apex_position',
            'without_base_position'
            ]
    train:
      params:
        persistent_workers: True
        pin_memory: False
        shuffle: True
    validation:
      params:
        persistent_workers: False
        pin_memory: False
        shuffle: False
    test:
      params:
        persistent_workers: False
        pin_memory: False
        shuffle: False

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        clamp: False
        batch_frequency: 200
        max_images: 16
        increase_log_steps: False
        rescale: False
        log_first_step: True
        log_images_kwargs:
          inpaint: False

  trainer:
    benchmark: True
    max_epochs: 10000
    check_val_every_n_epoch: 1 
