model:
  base_learning_rate: 1e-4   # set to target_lr by starting main.py with '--scale_lr False'
  target: daf_net.dafnet.DAFNetLightning
  params:
    modalities: ['cine']
    num_masks: 4
    learning_rate: 1e-4
    automated_pairing: false
    use_swa: true
    swa_start_epoch: 40
    swa_freq: 1
    
    scheduler_config: # 10000 warmup steps
      target: functions.lr_scheduler.LambdaLinearScheduler
      params:
        # warm_up_steps: [10000]
        warm_up_steps: [1000]
        cycle_lengths: [10000000000000]
        # f_start: [1.e-6]
        f_start: [0.1]
        f_max: [1.]
        f_min: [1.]

    loss_config:
      w_sup_M: 10.0
      w_adv_M: 1.0
      w_rec_X: 1.0
      w_adv_X: 1.0
      w_kl: 0.1
      w_rec_Z: 1.0
      restrict_channels: 3
    
    anatomy_encoder_config:
      target: models.anatomy_encoder.AnatomyEncoders
      params:
        modalities: ['cine', 'psir']
        in_channels: 1
        out_channels: 8
        base_channels: 64
        ch_mult: [1, 2, 4, 8, 16]
        norm_type: batch
        use_rounding: true
        bilinear: true
    
    modality_encoder_config:
      target: models.modality_encoder.ModalityEncoder
      params:
        resolution: 192
        in_channels: 1
        base_channels: 64
        anatomy_channels: 8
        ch_mult: [1, 2, 4, 8]
        latent_dim: 8
    
    segmentor_params_config:
      target: models.segmentor.Segmentor
      params:
        in_channels: 8
        num_classes: 4
        base_channels: 64
    
    # decoder_params_config:
    #   target: models.decoder.Decoder
    #   params:
    #     decoder_type: film
    #     decoder_params:
    #       in_channels: 8
    #       base_channels: 64
    #       modality_dim: 8
    #       num_layers: 4
    #     out_channels: 64

    decoder_params_config:
      target: models.decoder.Decoder
      params:
        decoder_type: spade
        decoder_params:
            resolution: 192  # the spatial resolution of the anatomy factor/ or the image
            base_channels: 128  # base channels of the SPADE blocks
            condition_channels: 8  # the anatomy factor will be set as the condition, the channels are equal to the number of anatomy factors
            ch_div: [1, 1, 1, 2, 4, 4]  # the channels division of the SPADE blocks
        out_channels: 32

    anatomy_fuser_config:
      target: models.anatomy_fuser.AnatomyFuser
      params:
        in_channels: 8
        resolution: 192
        control_points: [5, 5]
        order: 2
    
    d_mask_params:
      #  target: models.discriminator.BaseDiscriminator
      # params:
        in_channels: 4
        resolution: 192
        base_channels: 16
        ch_mult: [1, 2, 4, 8]
        use_spectral_norm: True
    
    d_image_params:
      # params:
        in_channels: 1
        resolution: 192
        base_channels: 16
        ch_mult: [1, 2, 4, 8, 16]
        use_spectral_norm: True

data:
  target: dataset.data_module.ACDCSegmentationDataModule
  params:
    dataset_dirpath: /public_bme2/bme-qihk/liaohx/PROJECTS/Multimodality_Segmentation/Data/ACDCSingleSliceDataset
    batch_size: 24
    num_workers: 8
    is_roi_resample: True
    roi_fixed_pixel_spacing: [0.89, 0.89]
    roi_resample_size: [192, 192]
    modality_vec_dim: 8
    training_groups: [
      'ACDC_Batch_0',
      'ACDC_Batch_1',
      'ACDC_Batch_2',
      'ACDC_Batch_3',
      'ACDC_Batch_4',
      'ACDC_Batch_5',
      'ACDC_Batch_6',
      'ACDC_Batch_7',
      'ACDC_Batch_8',
      ]
    testing_groups: [
      'ACDC_Batch_9',
      ]
    train:
      params:
        persistent_workers: True
        pin_memory: False
        shuffle: True
    validation:
      params:
        persistent_workers: False
        pin_memory: False
        shuffle: False
    test:
      params:
        persistent_workers: False
        pin_memory: False
        shuffle: False


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        clamp: False
        batch_frequency: 500
        max_images: 16
        increase_log_steps: False # False
        rescale: False
        log_first_step: True
        log_images_kwargs:
          inpaint: False

  trainer:
    benchmark: True
    max_epochs: 10000
    check_val_every_n_epoch: 1 
